-- Table T_SHR_INFO
CREATE TABLE T_SHR_INFO (
	PK_SHR_INFO			VARCHAR2(50)	DEFAULT sys_guid() NOT NULL,
	C_USERNAME			VARCHAR2(50)	NOT NULL,
    C_PLAN_TYPE         VARCHAR2(50)	NOT NULL,
	C_TOTAL_ALL_LINK	NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_TOTAL_SHORT_LINK	NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_TOTAL_CUSTOM_LINK	NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_TOTAL_PASS_LINK	NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_TOTAL_QR_LINK		NUMBER(20, 0)	NOT NULL	DEFAULT	0,

	C_CREATED_DATE		DATE			NOT NULL,
	C_CREATED_BY		VARCHAR2(50)	NOT NULL,
	C_UPDATED_DATE		DATE			NULL,
	C_UPDATED_BY		VARCHAR2(50)	NULL,

	CONSTRAINT T_SHR_INFO_PK PRIMARY KEY 
	(
		PK_SHR_INFO 
	)
	ENABLE 
);

CREATE UNIQUE INDEX IX_SHR_INFO_USERNAME ON T_SHR_INFO(C_USERNAME);

-- Table T_SHR_LINK
CREATE TABLE T_SHR_LINK (
    PK_SHR_LINK			VARCHAR2(50)	DEFAULT sys_guid() NOT NULL,
	C_USERNAME			VARCHAR2(50)	NOT NULL,
    C_NAME				VARCHAR2(200)	NOT NULL,
    C_SHORT_LINK		VARCHAR2(200)	NOT NULL,
    C_ORIGINAL_LINK		VARCHAR2(2000)	NOT NULL,
	C_IS_CUSTOM_LINK	NUMBER(1, 0)	NOT NULL,
	C_PASSWORD			VARCHAR2(50)	NULL,
	C_TOTAL_CLICK		NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_TOTAL_VIEW		NUMBER(20, 0)	NOT NULL	DEFAULT	0,
	C_DESCRIPTION		VARCHAR2(2000)	NULL,
	C_IS_ACTIVE			NUMBER(1, 0)	NOT NULL	DEFAULT	1,

	C_CREATED_DATE		DATE			NOT NULL,
	C_CREATED_BY		VARCHAR2(50)	NOT NULL,
	C_UPDATED_DATE		DATE			NULL,
	C_UPDATED_BY		VARCHAR2(50)	NULL,

	CONSTRAINT T_SHR_LINK_PK PRIMARY KEY 
	(
		PK_SHR_LINK 
	)
	ENABLE 
);

CREATE UNIQUE INDEX IX_SHR_LINK_USERNAME ON T_SHR_LINK(C_USERNAME);
CREATE UNIQUE INDEX IX_SHR_LINK_SHORT_LINK ON T_SHR_LINK(C_SHORT_LINK);